changelog:
  exclude:
    authors:
      - dalu-wins

  categories:
    - title: Breaking Changes 🛠
      commits:
        - breaking

    - title: Exciting New Features 🎉
      commits:
        - feat

    - title: Bug Fixes 🐛
      commits:
        - fix

    - title: Other Changes
      labels:
        - "*"
