name: Manual Release

on:
  workflow_dispatch: # Nur manuell startbar

jobs:
  test_and_build:
    name: Test & Build signed APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Decode Keystore
        run: echo "${{ secrets.APP_KEYSTORE_B64 }}" | base64 --decode > app/keystore.jks

      - name: Build Release APK
        env:
          APP_KEYSTORE_PASSWORD: ${{ secrets.APP_KEYSTORE_PASSWORD }}
          APP_KEY_ALIAS: ${{ secrets.APP_KEY_ALIAS }}
          APP_KEY_PASSWORD: ${{ secrets.APP_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v5
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk

  release:
    name: Run semantic-release & Create GitHub Release
    needs: test_and_build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download built artifact
        uses: actions/download-artifact@v6
        with:
          name: app-release
          path: app-release

      - name: List APK files
        run: |
          echo "Files downloaded to app-release/:"
          ls -R app-release

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches master --ci false
